-- AlterTable
ALTER TABLE "customers" ADD COLUMN     "discountPct" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "orders" ADD COLUMN     "discountAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "discountPct" DOUBLE PRECISION NOT NULL DEFAULT 0;
